#include "mptest_build.h"

#define RE_USE_CUSTOM_MALLOC 1
#define RE_MALLOC MPTEST_INJECT_MALLOC
#define RE_FREE MPTEST_INJECT_FREE
#define RE_REALLOC MPTEST_INJECT_REALLOC
#define RE_USE_CUSTOM_ASSERT 1
#define RE_ASSERT MPTEST_INJECT_ASSERT
