#ifndef TEST_CONFIG_H
#define TEST_CONFIG_H

#include "mptest_build.h"

#define MN_USE_CUSTOM_ALLOCATOR 1
#define MN_MALLOC MPTEST_INJECT_MALLOC
#define MN_FREE MPTEST_INJECT_FREE
#define MN_REALLOC MPTEST_INJECT_REALLOC
#define MN_USE_CUSTOM_ASSERT 1
#define MN_ASSERT MPTEST_INJECT_ASSERT

#endif
